DATA:
  batch_size: 4
  n_classes: 2

  root_dir: "data/oxford_pets_dataset"
  train_split_file: "annotations/trainval.txt"
  test_file: "annotations/test.txt"

  image_size: 256
  num_workers: 4

  TRANSFORMS:
    normalize_mean: [0.458, 0.456, 0.406]
    normalize_std: [0.229, 0.224, 0.225]
    train_random_flip_prob: 0.5

MODEL:
  in_channels: 3
  out_channels: 2
  base_channels: 64

TRAIN:
  num_epochs: 50
  lr: 0.0001

LOGGING:
  logging_dir: "artifacts/logs"
  images_dir: "artifacts/images/"